const constants = {
	ADD_CUSTOMER: 'ADD_CUSTOMER',
	UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
	DELETE_CUSTOMER: 'DELETE_CUSTOMER',
	DISPLAY_CUSTOMER: 'DISPLAY_CUSTOMER',
	RESET_CUSTOMER: 'RESET_CUSTOMER'
};

export default constants;
