const constants = {
	ADD_CUSTOMER: "ADD_CUSTOMER",
	UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
	DELETE_CUSTOMER: "DELETE_CUSTOMER",
	DISPLAY_CUSTOMER: "DISPLAY_CUSTOMER",
	CLEAR_CUSTOMER_VIEW: "CLEAR_CUSTOMER_VIEW"
}

export default constants
